/* ==== EDIT YOUR CONTENT HERE. Most of the site is built from this file. ==== */
const portfolioData = {
  name: "Ewaen Erhahon",
  title: "Business Analyst | Project Manager | Data & Process Improvement Analyst",
  location: "Birmingham, United Kingdom",
  tagline: "Turning business needs into clear requirements and practical solutions.",
  shortBio: "I am a Business Analysis intern at 10 Analytics with a background in Computer Engineering. I bring a technical perspective to understanding business needs and exploring practical solutions. My project experience includes stakeholder analysis, requirements documentation, process mapping and gap analysis.",
  about: [
    "I enjoy understanding how businesses operate, identifying problems and exploring practical ways to improve processes. My technical background helps me connect business needs with possible technology solutions.",
    "Through my training and project work, I have gained experience in stakeholder analysis, requirements documentation, process mapping, gap analysis and business case development. I use these techniques to examine current processes, describe the desired future state and explain the changes needed to bridge the gap.",
    "My portfolio includes projects involving mobile banking, HR process optimisation, insurance claims and brewery operations. These projects have helped me prepare RACI matrices, stakeholder communication plans, swimlane diagrams and business requirements.",
    "I bring curiosity, attention to detail and a willingness to learn. I value clear communication and collaboration, and I aim to understand the needs of the people affected by a proposed change."
  ],
  photo: "assets/images/profile.png",
  email: "walkerewaen@gmail.com",
  phone: "07867 047367",
  linkedin: "https://www.linkedin.com/in/ewaen-erhahon-420b70440",
  github: "https://github.com/walkerewaen-afk",
  resume: "assets/documents/Ewaen_Erhahon_BA_CV.pdf",
  resumeText: "View CV",
  formspreeEndpoint: "https://formspree.io/f/xwlvvrkl",
  skills: {
    "Business Analysis": ["Requirements elicitation and analysis","Stakeholder analysis and management","Business requirements documentation","User stories and acceptance criteria","Process mapping","Gap analysis","Root cause analysis","RACI matrices","Business case development","Options evaluation","UAT support"],
    "Data & Analytics": ["Data analysis","Data visualisation","Power BI dashboards","KPI development and monitoring","Operational reporting","Cost analysis","Budgeting and forecasting","Inventory analysis","Procurement trend analysis"],
    "Tools": ["Microsoft Excel","Power BI","Jira","Trello","Miro","Microsoft Word","PowerPoint","Google Workspace","Slack","Zoom"],
    "Methodologies": ["Agile","Scrum","Waterfall","Hybrid Agile-Waterfall","As-Is and To-Be analysis","SWOT analysis","Continuous process improvement"],
    "Other Skills": ["Cross-functional collaboration","Team supervision","Vendor and supplier management","Procurement coordination","Maintenance planning","Budget management","Change management support","Compliance awareness","Workshop facilitation","Problem-solving","Professional communication"]
  },
  experience: [
    { company:"10Alytics", role:"Business Analyst", location:"Remote", dates:"March 2025 – Present",
      summary:"Support business transformation and process improvement projects by analysing requirements, documenting workflows and collaborating with business and technical stakeholders.",
      achievements:["Prepared requirements documentation and user stories to guide solution development.","Created process maps that clarified workflows and proposed changes.","Developed Power BI dashboards to communicate project and business performance."],
      impact:"Supported clearer requirements, shared understanding between teams and better visibility of project performance.",
      tools:"Jira, Power BI, Trello, Slack, Zoom" },
    { company:"Gramen Petroserve Nigeria Limited", role:"Maintenance Supervisor", location:"Warri, Nigeria", dates:"August 2022 – April 2025",
      summary:"Led maintenance operations and improvement activities, combining team supervision, process review, budget management and vendor coordination.",
      achievements:["Introduced a preventive maintenance schedule that reduced equipment downtime by 20%.","Standardised repair procedures and parts usage, reducing repair costs by 15%.","Managed facility upgrade projects within financial constraints while meeting quality and compliance requirements."],
      impact:"Improved equipment availability, controlled maintenance expenditure and strengthened operational consistency.",
      tools:"Preventive maintenance schedules, repair records, departmental budgets, vendor documentation" },
    { company:"Gramen Petroserve Nigeria Limited", role:"Maintenance Officer", location:"Warri, Nigeria", dates:"August 2017 – August 2022",
      summary:"Supported operational reliability through maintenance planning, accurate record-keeping, inventory coordination and evaluation of equipment rental options.",
      achievements:["Maintained adherence to safety standards and statutory checks.","Improved parts-count accuracy and supported faster repairs through detailed operational records.","Negotiated equipment rental arrangements that saved approximately $10,000 annually."],
      impact:"Supported reliable operations, improved information accuracy and reduced equipment rental expenditure.",
      tools:"Inspection schedules, maintenance records, inventory logs, supplier quotations" }
  ],
  projects: [
    { id:"mobile-banking", name:"Mobile Banking Application: RACI Matrix", category:"Business Analysis",
      short:"Defined stakeholder responsibilities for ten activities involved in preparing a mobile banking application for launch.",
      tools:"RACI matrix (software not specified)", skills:["Stakeholder analysis","RACI mapping"],
      problem:"The project required several teams to coordinate development, security, testing and launch activities. Clear ownership was needed to prevent missed responsibilities and confusion over approvals.",
      objective:"Identify relevant stakeholders and define who is Responsible, Accountable, Consulted and Informed for each deliverable.",
      role:"Business Analysis trainee responsible for preparing the stakeholder responsibility matrix.",
      approach:"Stakeholder analysis and RACI responsibility mapping, using the supplied fintech scenario and ten project deliverables.",
      analysis:["Reviewed activities from scope and budget approval through post-launch monitoring.","Considered the business, technical, security and customer support stakeholders needed.","Mapped delivery responsibilities, approval ownership and consultation requirements."],
      findings:["The launch required coordination across business and technical teams.","Security testing and UAT needed clearly defined responsibilities.","Customer support training and post-launch monitoring needed ownership alongside development activities."],
      recommendations:["Validate the RACI assignments with stakeholders before delivery begins.","Review responsibilities when project scope or team membership changes."],
      outcome:"Prepared a RACI matrix covering ten project deliverables.",
      impact:"Intended to improve accountability and coordination. No implemented or measured impact was supplied." },
    { id:"hr-optimisation", name:"Dynamic Enterprise: HR Process Optimisation", category:"Business Analysis / Process Improvement",
      short:"Analysed fragmented HR operations and developed a proposal for a unified global Human Capital Management platform.",
      tools:"PowerPoint, stakeholder analysis matrix, power-interest matrix, RACI matrix", skills:["Options appraisal","Business case","Stakeholder engagement"],
      problem:"Separate regional HR systems created inconsistent processes, fragmented employee information, reporting limitations and compliance risks.",
      objective:"Recommend an approach to standardising HR processes and improving employee information, reporting and service consistency.",
      role:"Business Analysis contributor to stakeholder planning, problem analysis and the proposed business solution.",
      approach:"Stakeholder analysis, options appraisal, business case development and a proposed hybrid Agile-Waterfall delivery approach, based on the Dynamic Enterprise capstone scenario.",
      analysis:["Identified stakeholder groups and developed engagement and communication plans.","Analysed eight business problems affecting HR operations.","Compared maintaining existing systems, enhancing them and introducing a global cloud-based HCM platform."],
      findings:["Fragmented employee information limited reliable workforce reporting.","Inconsistent regional processes affected efficiency and employee experience.","Data migration, regulatory requirements and user adoption required careful planning."],
      recommendations:["Introduce a unified cloud-based HCM platform with appropriate regional requirements.","Use a phased rollout supported by data validation, stakeholder engagement and training."],
      outcome:"Produced stakeholder management artefacts, a business case, solution recommendations and a proposed implementation approach.",
      impact:"Expected benefits include reduced manual administration, improved workforce reporting and more consistent HR services. These benefits were proposed, not measured. Financial figures in the presentation were hypothetical." },
    { id:"redwood-insurance", name:"Redwood Insurance: Future-State Claims Process", category:"Process Improvement",
      short:"Documented a proposed seven-step insurance claims process and illustrated responsibilities using a swimlane diagram.",
      tools:"Seven-step process table, swimlane diagram", skills:["To-Be process mapping","Swimlane analysis"],
      problem:"The case study described a manual, fragmented claims process with delays, inconsistent communication and limited transparency.",
      objective:"Design a clearer future-state process covering claim submission, review, decision-making, payment and customer notification.",
      role:"Business Analysis trainee responsible for documenting the proposed workflow and swimlane diagram.",
      approach:"To-Be process mapping and swimlane responsibility analysis, based on the Redwood Insurance case study.",
      analysis:["Organised the proposed claims journey into seven activities.","Distinguished automated checks and routing from human investigation and approval.","Assigned activities across the customer, claims system, Claims Officer, manager and Finance."],
      findings:["Information checks and claim routing were candidates for automation.","Investigation and approval required defined human responsibility.","Payment applied to approved claims, with status updates and customer notification completing the workflow."],
      recommendations:["Introduce online submission, automated checks and routing.","Define approval authority and customer notification rules before implementation."],
      outcome:"Produced a seven-step To-Be process table and proposed swimlane diagram.",
      impact:"Intended to reduce manual handoffs and improve ownership and customer visibility. No implementation results or measured savings were supplied." },
    { id:"brewflow", name:"BrewFlow 360: Brewery Operations Gap Analysis", category:"Business Analysis / Process Improvement",
      short:"Compared current brewery operations with the desired future state and documented requirements for a proposed integrated operations system.",
      tools:"Gap analysis table, root-cause diagram, SWOT matrix, process maps, swimlane diagram, requirements traceability matrix", skills:["Gap analysis","Root cause analysis","Requirements traceability"],
      problem:"Manual records, unreliable forecasting, ageing equipment and communication gaps contributed to production delays, quality inconsistency and inventory shortages.",
      objective:"Identify operational gaps and define requirements supporting better production planning, traceability, inventory visibility and coordination.",
      role:"Business Analysis contributor to gap analysis, process mapping and requirements documentation.",
      approach:"As-Is and To-Be analysis, root cause analysis, SWOT analysis and requirements traceability, based on the brewery capstone scenario and BrewFlow 360 requirements document.",
      analysis:["Compared current and desired practices across forecasting, production, quality, inventory and workforce sustainability.","Examined how manual information and communication gaps affected operational workflows.","Linked business problems to objectives, business requirements and functional requirements."],
      findings:["Forecasting relied on intuition and informal conversations.","Manual recipes, fermentation records and inventory updates limited consistency and visibility.","Equipment reliability required physical improvements alongside the proposed digital system."],
      recommendations:["Introduce an integrated platform for forecasting, production records, quality control and inventory information.","Coordinate implementation with equipment improvements, data cleansing, training and agreed approval responsibilities."],
      outcome:"Produced a gap analysis, process maps and a requirements document for the proposed BrewFlow 360 solution.",
      impact:"Expected benefits include improved planning, traceability and coordination. Implementation was not confirmed, and numerical success targets remained subject to stakeholder agreement." }
  ]
};
